2020-12-10 16:36:45,957 ERROR 49810 [-/127.0.0.1/-/7ms GET /query?address=5G1QfcZWMREnH52Nngsh3GwHBeJCs9faPudC4s9NHL9qeu7Q] nodejs.Error: WebSocket is not connected
    at assert (/Users/libaozhong/熊涛/node/attemper/node_modules/@polkadot/rpc-provider/node_modules/@polkadot/util/assert.js:34:11)
    at /Users/libaozhong/熊涛/node/attemper/node_modules/@polkadot/rpc-provider/ws/index.js:457:26
    at new Promise (<anonymous>)
    at WsProvider.send (/Users/libaozhong/熊涛/node/attemper/node_modules/@polkadot/rpc-provider/ws/index.js:455:12)
    at callWithRegistry (/Users/libaozhong/熊涛/node/attemper/node_modules/@polkadot/rpc-core/index.js:259:40)
    at Observable._subscribe (/Users/libaozhong/熊涛/node/attemper/node_modules/@polkadot/rpc-core/index.js:266:9)
    at Observable._trySubscribe (/Users/libaozhong/熊涛/node/attemper/node_modules/rxjs/internal/Observable.js:44:25)
    at Observable.subscribe (/Users/libaozhong/熊涛/node/attemper/node_modules/rxjs/internal/Observable.js:30:22)
    at Observable.ConnectableObservable.connect (/Users/libaozhong/熊涛/node/attemper/node_modules/rxjs/internal/observable/ConnectableObservable.js:47:18)
    at RefCountOperator.call (/Users/libaozhong/熊涛/node/attemper/node_modules/rxjs/internal/operators/refCount.js:33:49)

pid: 49810
hostname: libaozhongdeMacBook-Pro.local

2020-12-10 19:47:54,685 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 1785529ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

2020-12-10 19:55:03,298 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 428605ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

2020-12-10 20:10:48,261 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 944955ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

2020-12-10 22:38:20,430 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 8832144ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

2020-12-10 23:30:55,215 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 174496ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

2020-12-10 23:38:12,265 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 437043ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

2020-12-11 09:32:33,423 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 35661143ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

2020-12-11 09:47:45,150 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 871707ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

