2020-12-10 14:37:49,849 INFO 49771 [egg-logrotator] agent logger reload: got log-reload message
2020-12-10 19:47:54,687 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 1785529ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

2020-12-10 19:55:03,298 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 428605ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

2020-12-10 20:10:48,261 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 944955ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

2020-12-10 22:38:20,433 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 8832144ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

2020-12-10 23:30:55,216 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 174496ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

2020-12-10 23:38:12,266 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 437043ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

2020-12-11 09:32:33,423 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 35661143ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

2020-12-11 09:47:45,152 ERROR 49771 nodejs.ClusterClientNoResponseError: client no response in 871707ms exceeding maxIdleTime 60000ms, maybe the connection is close on other side.
    at Timeout._onTimeout (/Users/libaozhong/熊涛/node/attemper/node_modules/cluster-client/lib/leader.js:77:23)
    at listOnTimeout (internal/timers.js:531:17)
    at processTimers (internal/timers.js:475:7)
name: "ClusterClientNoResponseError"
pid: 49771
hostname: libaozhongdeMacBook-Pro.local

